# Generated by Django 4.2.3 on 2023-07-18 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppFixB1', '0002_app_company_usercompany_report_appcompany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='user',
        ),
        migrations.AddField(
            model_name='app',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
