# Generated by Django 4.2.3 on 2023-07-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFixB1', '0003_remove_app_user_app_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
