# Generated by Django 4.2.3 on 2023-07-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFixB1', '0004_alter_app_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_solved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
