# Generated by Django 4.2.3 on 2023-07-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFixB1', '0005_alter_report_date_created_alter_report_date_solved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=255),
        ),
    ]
