# Generated by Django 4.2.3 on 2023-07-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFixB1', '0006_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
